AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create a CloudFront distribution.

Parameters:
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket
  MyApi:
    Type: String
    Description: API Id
    Default: kjhcxpht7d
  CostCenter:
    Type: String
    Description: "Cost Center"
    Default: liberty
  Stage:
    Type: String
    Description: "Stage"
    AllowedValues:
      - dev
      - stg
      - pdn
    Default: dev

Resources:
  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'Access identity for ${CostCenter}'

  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - Id: !Sub '${S3BucketName}-origin'
            DomainName: !Sub '${S3BucketName}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: !Sub '${S3BucketName}-origin'
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
      Tags:
      - Key: Cost Center
        Value: !Ref CostCenter
      - Key: Stage
        Value: !Ref Stage
      - Key: lm_troux_uid
        Value: 123

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'

  OriginRequestPolicyApiGateway:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: OriginRequestPolicyApiGateway
        QueryStringsConfig:
          QueryStringBehavior: all
        CookiesConfig:
          CookieBehavior: all
        HeadersConfig:
          HeaderBehavior: allExcept
          Headers: 
            - host

  CachePolicyDisabled:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: Policy with caching disabled
        Name: CachePolicyApiDisabled
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingBrotli: false
          EnableAcceptEncodingGzip: false
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
  
  CloudFrontDistributionApi:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - POST
            - DELETE 
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: apiOrigin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: !Ref CachePolicyDisabled
          OriginRequestPolicyId: !Ref OriginRequestPolicyApiGateway
        DefaultRootObject: index.html
        Origins:
          - Id: apiOrigin
            DomainName: !Sub "${MyApi}.execute-api.${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: 
                - TLSv1.2
      Tags:
      - Key: Cost Center
        Value: !Ref CostCenter
      - Key: Stage
        Value: !Ref Stage
      - Key: lm_troux_uid
        Value: 123

Outputs:
  CloudFrontDistributionApiId:
    Description: ID de la distribución de CloudFront API
    Value: !Ref CloudFrontDistributionApi
    Export:
      Name: !Sub "CloudFrontDistributionApiId-${Stage}"

  CloudFrontDomainNameApi:
    Description: Dominio de CloudFront API
    Value: !GetAtt CloudFrontDistributionApi.DomainName
    Export:
      Name: !Sub "CloudFrontDomainNameApi-${Stage}"

  CloudFrontDistributionS3Id:
    Description: The ID of the CloudFront distribution
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "CloudFrontDistributionS3Id-${Stage}"

  CloudFrontDomainNameS3:
    Description: The domain name of the CloudFront distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "CloudFrontDomainNameS3-${Stage}"
