AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Create Api Keys'

Parameters:
  CostCenter:
    Type: String
    Description: "Cost Center"
    Default: liberty

  Stage:
    Type: String
    Description: "Stage"
    AllowedValues:
      - dev
      - stg
      - pdn
    Default: dev

  MyApi:
    Type: String
    Description: "Api Rest ID"
    Default: kjhcxpht7d

Resources:
  Deployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref MyApi
      Description: !Sub My deployment - ${Stage}
      StageName: !Ref Stage

  MyApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: true
      Name: !Sub apikey-${Stage}-${CostCenter}
      Description: API Key for My API
      Tags:
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Stage
          Value: !Ref Stage
        - Key: lm_troux_uid
          Value: 123

  MyUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref MyApi
          Stage: !Ref Stage
      Description: Usage Plan for My API
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 200
        RateLimit: 100
      Tags:
        - Key: Cost Center
          Value: !Ref CostCenter
        - Key: Stage
          Value: !Ref Stage
        - Key: lm_troux_uid
          Value: 123
    DependsOn: Deployment

  MyUsagePlanApiKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref MyApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref MyUsagePlan

Outputs:
  ApiDeploymentId:
    Description: The deployment ID of the API Gateway
    Value: !Ref Deployment
    Export:
      Name: !Sub "ApiDeploymentId-${Stage}"

  ApiKeyId:
    Description: The API Key ID
    Value: !Ref MyApiKey
    Export:
      Name: !Sub "ApiKeyId-${Stage}"

  UsagePlanId:
    Description: The Usage Plan ID
    Value: !Ref MyUsagePlan
    Export:
      Name: !Sub "UsagePlanId-${Stage}"

  UsagePlanKeyId:
    Description: The Usage Plan Key ID
    Value: !Ref MyUsagePlanApiKey
    Export:
      Name: !Sub "UsagePlanKeyId-${Stage}"

  ApiEndpoint:
    Description: The endpoint of the API
    Value: !Sub https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}
    Export:
      Name: !Sub "ApiEndpoint-${Stage}"