AWSTemplateFormatVersion: '2010-09-09'
Description: Master template

Parameters:
  CostCenter:
    Type: String
    Description: "Cost Center"
    Default: liberty

  Stage:
    Type: String
    Description: "Stage"
    AllowedValues:
      - dev
      - stg
      - pdn
    Default: dev

  BucketFunctionName:
    Type: String
    Description: "Bucket Name Functions Deploy"
    Default: functions-liberty

Resources:
  VPCStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://cloudformation-liberty.s3.amazonaws.com/aws/liberty/vpc/vpc.liberty.yml'
      Parameters:
        CostCenter: !Ref CostCenter
        Stage: !Ref Stage
      TimeoutInMinutes: '10'
  
  EC2Stack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://cloudformation-liberty.s3.amazonaws.com/aws/liberty/ec2/security.group.yml'
      Parameters:
        CostCenter: !Ref CostCenter
        Stage: !Ref Stage
        VpcId: !GetAtt VPCStack.Outputs.VpcId
      TimeoutInMinutes: '10'
    DependsOn: 
      - VPCStack

  ApiGatewayStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://cloudformation-liberty.s3.amazonaws.com/aws/liberty/api-gateway/api.liberty.yml'
      Parameters:
        CostCenter: !Ref CostCenter
        Stage: !Ref Stage
      TimeoutInMinutes: '10'

  DynamoStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://cloudformation-liberty.s3.amazonaws.com/aws/liberty/dynamo/dynamo.liberty.yml'
      Parameters:
        CostCenter: !Ref CostCenter
        Stage: !Ref Stage
      TimeoutInMinutes: '10'

  S3Stack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://cloudformation-liberty.s3.amazonaws.com/aws/liberty/s3/s3.liberty.yml'
      Parameters:
        CostCenter: !Ref CostCenter
        Stage: !Ref Stage
      TimeoutInMinutes: '10'
  
  LambdaStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://cloudformation-liberty.s3.amazonaws.com/aws/liberty/lambda/lambda.liberty.yml'
      Parameters:
        CostCenter: !Ref CostCenter
        Stage: !Ref Stage
        BucketFunctionName: !Ref BucketFunctionName
        S3BucketName: !GetAtt S3Stack.Outputs.S3BucketName
        DynamoTableName: !GetAtt DynamoStack.Outputs.DynamoTableName
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        SecurityGroup: !GetAtt EC2Stack.Outputs.SecurityGroupId
        MyApi: !GetAtt ApiGatewayStack.Outputs.MyApi
        S3ResourceId: !GetAtt ApiGatewayStack.Outputs.S3ResourceId
        DynamoResourceId: !GetAtt ApiGatewayStack.Outputs.DynamoResourceId
        RequestValidatorId: !GetAtt ApiGatewayStack.Outputs.RequestValidatorId
      TimeoutInMinutes: '10'

  ApiKeyStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://cloudformation-liberty.s3.amazonaws.com/aws/liberty/api-gateway/api-key.liberty.yml'
      Parameters:
        CostCenter: !Ref CostCenter
        Stage: !Ref Stage
        MyApi: !GetAtt ApiGatewayStack.Outputs.MyApi
      TimeoutInMinutes: '10'
    DependsOn: 
      - LambdaStack
      - ApiGatewayStack

  CloudFrontStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://cloudformation-liberty.s3.amazonaws.com/aws/liberty/cloudfront/cloudfront.liberty.yml'
      Parameters:
        S3BucketName: !GetAtt S3Stack.Outputs.S3BucketName
        CostCenter: !Ref CostCenter
        Stage: !Ref Stage
        MyApi: !GetAtt ApiGatewayStack.Outputs.MyApi
      TimeoutInMinutes: '10'
    DependsOn: 
      - ApiGatewayStack
      - S3Stack
